DROP TABLE IF EXISTS localidad;
CREATE TABLE localidad(
	id integer PRIMARY KEY,
	nombre text NOT NULL
);


INSERT INTO localidad (id,nombre) VALUES (23001,"Albanchez de Magina");
INSERT INTO localidad (id,nombre) VALUES (23002,"Alcala la Real");
INSERT INTO localidad (id,nombre) VALUES (23003,"Alcaudete");
INSERT INTO localidad (id,nombre) VALUES (23004,"Aldeaquemada");
INSERT INTO localidad (id,nombre) VALUES (23005,"Andujar");
INSERT INTO localidad (id,nombre) VALUES (23006,"Arjona");
INSERT INTO localidad (id,nombre) VALUES (23007,"Arjonilla");
INSERT INTO localidad (id,nombre) VALUES (23008,"Arquillos");
INSERT INTO localidad (id,nombre) VALUES (23905,"Arroyo del Ojanco");
INSERT INTO localidad (id,nombre) VALUES (23009,"Baeza");
INSERT INTO localidad (id,nombre) VALUES (23010,"Bailen");
INSERT INTO localidad (id,nombre) VALUES (23011,"Baños de la Encina");
INSERT INTO localidad (id,nombre) VALUES (23012,"Beas de Segura");
INSERT INTO localidad (id,nombre) VALUES (23902,"Bedmar y Garciez");
INSERT INTO localidad (id,nombre) VALUES (23014,"Begijar");
INSERT INTO localidad (id,nombre) VALUES (23015,"Belmez de la Moraleda");
INSERT INTO localidad (id,nombre) VALUES (23016,"Benatae");
INSERT INTO localidad (id,nombre) VALUES (23017,"Cabra de Santo Cristo");
INSERT INTO localidad (id,nombre) VALUES (23018,"Cambil");
INSERT INTO localidad (id,nombre) VALUES (23019,"Campillo de Arenas");
INSERT INTO localidad (id,nombre) VALUES (23020,"Canena");
INSERT INTO localidad (id,nombre) VALUES (23021,"Carboneros");
INSERT INTO localidad (id,nombre) VALUES (23901,"Carcheles");
INSERT INTO localidad (id,nombre) VALUES (23024,"La Carolina");
INSERT INTO localidad (id,nombre) VALUES (23025,"Castellar");
INSERT INTO localidad (id,nombre) VALUES (23026,"Castillo de Locubin");
INSERT INTO localidad (id,nombre) VALUES (23027,"Cazalilla");
INSERT INTO localidad (id,nombre) VALUES (23028,"Cazorla");
INSERT INTO localidad (id,nombre) VALUES (23029,"Chiclana de Segura");
INSERT INTO localidad (id,nombre) VALUES (23030,"Chilluevar");
INSERT INTO localidad (id,nombre) VALUES (23031,"Escañuela");
INSERT INTO localidad (id,nombre) VALUES (23032,"Espeluy");
INSERT INTO localidad (id,nombre) VALUES (23033,"Frailes");
INSERT INTO localidad (id,nombre) VALUES (23034,"Fuensanta de Martos");
INSERT INTO localidad (id,nombre) VALUES (23035,"Fuente del Rey");
INSERT INTO localidad (id,nombre) VALUES (23037,"Genave");
INSERT INTO localidad (id,nombre) VALUES (23038,"La Guardia de Jaen");
INSERT INTO localidad (id,nombre) VALUES (23039,"Guarroman");
INSERT INTO localidad (id,nombre) VALUES (23041,"Higuera de Calatrava");
INSERT INTO localidad (id,nombre) VALUES (23042,"Hinojares");
INSERT INTO localidad (id,nombre) VALUES (23043,"Hornos");
INSERT INTO localidad (id,nombre) VALUES (23044,"Huelma");
INSERT INTO localidad (id,nombre) VALUES (23045,"Huesa");
INSERT INTO localidad (id,nombre) VALUES (23046,"Ibros");
INSERT INTO localidad (id,nombre) VALUES (23047,"La Iruela");
INSERT INTO localidad (id,nombre) VALUES (23048,"Iznatoraf");
INSERT INTO localidad (id,nombre) VALUES (23049,"Jabalquinto");
INSERT INTO localidad (id,nombre) VALUES (23050,"Jaen");
INSERT INTO localidad (id,nombre) VALUES (23051,"Jamilena");
INSERT INTO localidad (id,nombre) VALUES (23052,"Jimena");
INSERT INTO localidad (id,nombre) VALUES (23053,"Jodar");
INSERT INTO localidad (id,nombre) VALUES (23040,"Lahigera");
INSERT INTO localidad (id,nombre) VALUES (23054,"Larva");
INSERT INTO localidad (id,nombre) VALUES (23055,"Linares");
INSERT INTO localidad (id,nombre) VALUES (23056,"Lopera");
INSERT INTO localidad (id,nombre) VALUES (23057,"Lupion");
INSERT INTO localidad (id,nombre) VALUES (23058,"Mancha Real");
INSERT INTO localidad (id,nombre) VALUES (23059,"Marmolejo");
INSERT INTO localidad (id,nombre) VALUES (23060,"Martos");
INSERT INTO localidad (id,nombre) VALUES (23061,"Menjibar");
INSERT INTO localidad (id,nombre) VALUES (23062,"Montizon");
INSERT INTO localidad (id,nombre) VALUES (23063,"Navas de San Juan");
INSERT INTO localidad (id,nombre) VALUES (23064,"Noalejo");
INSERT INTO localidad (id,nombre) VALUES (23065,"Ocera");
INSERT INTO localidad (id,nombre) VALUES (23066,"Peal de Becerro");
INSERT INTO localidad (id,nombre) VALUES (23067,"Pegalajar");
INSERT INTO localidad (id,nombre) VALUES (23069,"Porcuna");
INSERT INTO localidad (id,nombre) VALUES (23070,"Pozo Alcon");
INSERT INTO localidad (id,nombre) VALUES (23071,"Puente de Genave");
INSERT INTO localidad (id,nombre) VALUES (23072,"La Puerta de Segura");
INSERT INTO localidad (id,nombre) VALUES (23073,"Quesada");
INSERT INTO localidad (id,nombre) VALUES (23074,"Rus");
INSERT INTO localidad (id,nombre) VALUES (23075,"Sabiote");
INSERT INTO localidad (id,nombre) VALUES (23076,"Santa Elena");
INSERT INTO localidad (id,nombre) VALUES (23077,"Santiago de Calatraba");
INSERT INTO localidad (id,nombre) VALUES (23904,"Santiago-Portones");
INSERT INTO localidad (id,nombre) VALUES (23079,"Santiesteban del Puerto");
INSERT INTO localidad (id,nombre) VALUES (23080,"Santo Tome");
INSERT INTO localidad (id,nombre) VALUES (23081,"Segura de la Sierra");
INSERT INTO localidad (id,nombre) VALUES (23082,"Siles");
INSERT INTO localidad (id,nombre) VALUES (23084,"Sorihuela de Guadalimar");
INSERT INTO localidad (id,nombre) VALUES (23085,"Torreblascopedro");
INSERT INTO localidad (id,nombre) VALUES (23086,"Torre del Campo");
INSERT INTO localidad (id,nombre) VALUES (23087,"Torredonjimeno");
INSERT INTO localidad (id,nombre) VALUES (23088,"Torreperojil");
INSERT INTO localidad (id,nombre) VALUES (23090,"Torres");
INSERT INTO localidad (id,nombre) VALUES (23091,"Torres de Albanchez");
INSERT INTO localidad (id,nombre) VALUES (23092,"Ubeda");
INSERT INTO localidad (id,nombre) VALUES (23093,"Valdepeñas de Jaen");
INSERT INTO localidad (id,nombre) VALUES (23094,"Vilches");
INSERT INTO localidad (id,nombre) VALUES (23095,"Villacarrillo");
INSERT INTO localidad (id,nombre) VALUES (23096,"Villanueva de la Reina");
INSERT INTO localidad (id,nombre) VALUES (23097,"Villanueva del Arzovispo");
INSERT INTO localidad (id,nombre) VALUES (23098,"Villadompardo");
INSERT INTO localidad (id,nombre) VALUES (23099,"Los villares");
INSERT INTO localidad (id,nombre) VALUES (23101,"Villarrodrigo");
INSERT INTO localidad (id,nombre) VALUES (23903,"Villatorres");

